export const GURGAON_SOCIETIES: string[] = [
  "DLF The Crest",
  "DLF The Camellias",
  "DLF The Aralias",
  "DLF The Magnolias",
  "DLF Park Place",
  "DLF Belaire",
  "DLF Carlton Estate",
  "DLF Wellington Estate",
  "DLF Regency Park I",
  "DLF Regency Park II",
  "DLF Princeton Estate",
  "DLF Richmond Park",
  "DLF Trinity Towers",
  "DLF Icon",
  "DLF Hamilton Court",
  "DLF Pinnacle",
  "DLF Summit",
  "DLF Exclusive Floors",
  "DLF Alameda",
  "DLF Privana West",
  "DLF Privana South",
  "M3M Golf Estate",
  "M3M Merlin",
  "M3M St. Andrews",
  "M3M Latitude",
  "M3M Heights",
  "M3M Skycity",
  "M3M Natura",
  "M3M Crown",
  "M3M Capital",
  "M3M Antalya Hills",
  "M3M Soulitude",
  "M3M Sierra",
  "M3M Polo Suites",
  "M3M Woodshire",
  "Ireo Grand Arch",
  "Ireo Victory Valley",
  "Ireo Skyon",
  "Ireo Uptown",
  "Ireo Corridors",
  "Ireo Gurgaon Hills",
  "Ireo The Corridors",
  "Ireo City",
  "Bestech Park View Spa",
  "Bestech Park View Ananda",
  "Bestech Park View Sanskruti",
  "Bestech Altura",
  "Bestech Grand Spa",
  "Bestech Sky Suites",
  "Tata Raisina Residency",
  "Tata Primanti",
  "Godrej Summit",
  "Godrej Air",
  "Godrej Nature Plus",
  "Godrej Meridien",
  "Godrej Aristocrat",
  "Godrej Miraya",
  "Sobha City",
  "Sobha International City",
  "Sobha Aranya",
  "Emaar Palm Springs",
  "Emaar Palm Terraces",
  "Emaar Palm Hills",
  "Emaar Marbella",
  "Emaar Emerald Estate",
  "Emaar DigiHomes",
  "Emaar Imperial Gardens",
  "Emaar Gurgaon Greens",
  "Emaar The Palm Drive",
  "Emaar Urban Oasis",
  "Vipul Greens",
  "Vipul Belmonte",
  "Vipul Lavanya",
  "Vipul World",
  "Central Park Resorts",
  "Central Park Flower Valley",
  "Central Park Bellevue",
  "Central Park Cerise Suites",
  "Central Park The Room",
  "Unitech Fresco",
  "Unitech Escape",
  "Unitech Harmony",
  "Unitech Heritage City",
  "Unitech South City Heights",
  "Unitech The Close",
  "Unitech The Residences",
  "Unitech Sunbreeze",
  "Unitech Nirvana Country",
  "Nirvana Courtyard",
  "Nirvana Cedar Crest",
  "Malibu Towne",
  "Sispal Vihar",
  "Orchid Island",
  "Orchid Petals",
  "Orchid Gardens",
  "The Hibiscus",
  "The Lilac",
  "Parsvnath Exotica",
  "Parsvnath Green Ville",
  "Parsvnath Privilege",
  "BPTP Freedom Park Life",
  "BPTP Park Serene",
  "BPTP Astaire Gardens",
  "BPTP Terra",
  "BPTP Amstoria",
  "BPTP Pedestal",
  "BPTP Amaario",
  "BPTP Spacio",
  "Raheja Atharva",
  "Raheja Revanta",
  "Raheja Vedaanta",
  "Raheja Navodaya",
  "Raheja Sampada",
  "Raheja Shilas",
  "Raheja Maheshwara",
  "ATS Tourmaline",
  "ATS Triumph",
  "ATS Kocoon",
  "ATS Marigold",
  "ATS Homekraft Sanctuary 105",
  "ATS Grandstand",
  "Experion Windchants",
  "Experion Heartsong",
  "Experion The Westerlies",
  "Experion One42",
  "Experion Nova",
  "Signature Global Solera",
  "Signature Global City 37D",
  "Signature Global City 81",
  "Signature Global City 92",
  "Signature Global Park",
  "Signature Global Deluxe DXP",
  "Signature Global Titanium SPR",
  "Smart World Orchard",
  "Smart World Orchard Avenue",
  "Smart World Gems",
  "Smart World One DXP",
  "Smart World Sky Arc",
  "Smart World The Edition",
  "Adani M2K Oyster Grande",
  "Adani Samsara",
  "Adani Aangan",
  "Adani Brahma Samsara",
  "SS The Leaf",
  "SS Hibiscus",
  "SS Linden",
  "SS Almeria",
  "SS Omnia",
  "Eldeco Accolade",
  "Eldeco Mansionz",
  "Eldeco Fairway Reserve",
  "Tulip Violet",
  "Tulip White",
  "Tulip Orange",
  "Tulip Lemon",
  "Tulip Ivory",
  "Tulip Purple",
  "Mapsko Mount Ville",
  "Mapsko Casa Bella",
  "Mapsko Royale Ville",
  "Vatika Emilia",
  "Vatika Seven Lamps",
  "Vatika Sovereign Park",
  "Vatika Lifestyle Homes",
  "Vatika Xpressions",
  "Vatika India Next",
  "Mahindra Luminare",
  "Mahindra Aura",
  "Paras Dews",
  "Paras Quartier",
  "Paras Irene",
  "Paras Floret",
  "AIPL The Peaceful Homes",
  "AIPL Zen Residences",
  "AIPL Club Residences",
  "Pioneer Park",
  "Pioneer Presidia",
  "Pioneer Araya",
  "Corona Optus",
  "Corona Gracieux",
  "Spaze Privy",
  "Spaze Privy AT4",
  "Spaze Privy The Address",
  "Spaze Kalistaa",
  "Ramprastha The Edge Towers",
  "Ramprastha Primera",
  "Ramprastha Skyz",
  "Ansal Esencia",
  "Ansal Heights",
  "Ansal API Versalia",
  "ROF Aalayas",
  "ROF Ambliss",
  "ROF Insignia Park",
  "Trevoc Royal Residences",
  "TARC Ishva",
  "Conscient Hines Elevate",
  "Conscient Heritage Max",
  "MRG Crown",
  "MRG World Ultimus",
  "Grand Iva",
  "DLF The Ultima",
  "DLF The Ultima Phase II",
  "GLS Avenue 81",
  "GLS Avenue 81 Phase II",
  "Landmark The Homes 81",
  "Bestech Park View Grand Spa",
  "Bestech Park View Ananda Villas",
  "Mapsko Paradise",
  "Mapsko Royal Ville Villas",
  "Vatika Boulevard Residences",
  "Vatika Boulevard Heights",
  "Vatika City Homes",
  "Vatika Express City",
  "SS Cendana",
  "SS Strada",
  "SS The Coralwood",
  "SS The Hibiscus Phase II",
  "Orris Aster Court",
  "Orris Carnation Residency",
  "Orris Greenbay Golf Village",
  "Orris Woodview Residences",
  "Orris Market City Homes",
  "ROF Ananda",
  "ROF Atulyas",
  "ROF Pravasa",
  "ROF Normanton Park",
  "Sare Crescent Parc",
  "Sare Home",
  "Sare Green Parc",
  "Sidhartha NCR One",
  "Sidhartha Hexa",
  "Pyramid Elite",
  "Pyramid Heights",
  "Pyramid Urban Homes",
  "Pyramid Fusion Homes",
  "Pyramid Infinity",
  "Pyramid Pride",
  "GLS South Avenue",
  "GLS Arawali Homes",
  "GLS Hub Homes",
  "Alpha G Corp GurgaonOne 84",
  "Alpha G Corp Sky Villas",
  "Alpha G Corp Carlton Estate",
  "Casa Bella Gold",
  "Casa Bella Apartments",
  "Spaze Arrow",
  "Spaze Privy The Address Villas",
  "Pivotal Devaan",
  "Pivotal Riddhi Siddhi",
  "Pivotal Paradise",
  "Karmyogi Apartments",
  "Karmyogi Greens",
  "Ashiana Mulberry",
  "Ashiana Amarah",
  "Ashiana Anmol",
  "Shree Vardhman Flora",
  "Shree Vardhman Victoria",
  "Shree Vardhman Olive",
  "Shree Vardhman Green Court",
  "Shree Vardhman Mantra",
  "Breez Global Heights",
  "Breez Flora Avenue",
  "Breez Carnival",
  "Breez Global Hill View",
  "HCBS Sports Ville",
  "HCBS Twin Horizon",
  "HCBS Twin Arcade",
  "HCBS Aqualibrium",
  "Zara Aavaas",
  "Zara Rossa",
  "Zara Elite Homes",
  "Lotus Greens Residency",
  "Lotus Homz",
  "Lotus Elise",
  "CHD Avenue 71",
  "CHD Vann",
  "ILD Greens",
  "ILD Grand",
  "ILD Arete",
  "ILD Spire Greens",
  "RPS Savana",
  "RPS Palm Drive",
  "AWHO Shanti Vihar",
  "AWHO Anandam",
  "JMS The Nation",
  "JMS Premier Floors",
  "JMS Prime Land",
  "Trehan Iris Broadway Residences",
  "Trehan Luxury Floors",
  "Yashika 104",
  "Yashika Homes",
  "Neo Centra",
  "Neo Square Residency",
  "One Indiabulls Gurgaon",
  "Indiabulls Centrum Park",
  "Indiabulls Enigma",
  "Indiabulls Estate Club",
  "KPDK Newtown Square",
  "Ramsons Kshitij",
  "Saan Verdante",
];

export function searchSocieties(query: string, limit = 10): string[] {
  const q = query.trim().toLowerCase();
  if (!q) return GURGAON_SOCIETIES.slice(0, limit);
  return GURGAON_SOCIETIES.filter((s) => s.toLowerCase().includes(q)).slice(0, limit);
}
